const $=s=>document.querySelector(s),cart=$('#cart'),detailDialog=$('#product-dialog'),items=[];
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n),number=n=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(n);
let selected=null,selectedQty=1,selectedOption=0,toastTimer,view='balcao',page=1;
const groups=[['balcao','Todo o balcão','snack','balcao'],['fritos','Salgados fritos','snack','balcao'],['assados','Salgados assados','snack','balcao'],['bebidas','Bebidas geladas','cup','balcao'],['sucos','Sucos e vitaminas','cup','balcao'],['quentes','Cafés e bebidas quentes','cup','balcao'],['encomendas','Todas as encomendas','cake','encomendas'],['bolos','Bolos por quilo','cake','encomendas'],['doces','Doces para festa','cake','encomendas'],['salgados-festa','Salgados para festa','snack','encomendas'],['combos','Combos para festa','cake','encomendas'],['sob-medida','Bolo personalizado','cake','especial'],['buffet','Buffet livre','snack','especial']];
const icon=type=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${type==='cup'?'<path d="M5 8h12v9a4 4 0 0 1-4 4H9a4 4 0 0 1-4-4V8Z"/><path d="M17 9h2a3 3 0 0 1 0 6h-2M8 3v2m4-3v3"/>':type==='cake'?'<path d="M3 13h18v8H3zM3 13l9-6 9 6M12 7V3M6 17h12"/>':'<path d="M3 17h18M5 17v-2a7 7 0 0 1 14 0v2M12 6V4M9 21h6"/>'}</svg>`;
function groupCount(id){return CakeCatalog.selectProducts(CAKE_MENU,id,'').total}
let lastScope='';for(const [id,name,type,scope]of groups){if(lastScope!==scope){const label=document.createElement('p');label.className='nav-section-label';label.textContent=scope==='balcao'?'BALCÃO':scope==='encomendas'?'ENCOMENDAS':'NA CAKE';$('#category-nav').append(label);lastScope=scope}const a=document.createElement('a');a.href='#'+id;a.innerHTML=icon(type);const text=document.createElement('span');text.textContent=name;a.append(text);const count=groupCount(id);if(count){const s=document.createElement('small');s.textContent=count;a.append(s)}a.onclick=e=>{e.preventDefault();selectView(id)};$('#category-nav').append(a)}
function selectView(id,scroll=true){view=groups.some(g=>g[0]===id)?id:'balcao';page=1;$('#search').value='';history.replaceState(null,'','#'+view);renderCatalog();if(scroll)scrollCatalog()}
function scrollCatalog(){const target=['sob-medida','buffet'].includes(view)?$('#'+view):$('#catalog-toolbar');target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}
function photo(product){const el=document.createElement('span');el.className='product-photo';if(product.image){if(product.crop){const [w,h,x,y,cw,ch]=product.crop;el.style.backgroundImage=`url("${product.image}")`;el.style.backgroundSize=`${w/cw*100}% ${h/ch*100}%`;el.style.backgroundPosition=`${x/(w-cw)*100}% ${y/(h-ch)*100}%`;el.setAttribute('role','img');el.setAttribute('aria-label',product.imageAlt||'Imagem ilustrativa de '+product.name)}else{const img=document.createElement('img');img.src=product.image;img.alt=product.imageAlt||'Imagem ilustrativa de '+product.name;img.loading='lazy';el.append(img)}}else{el.classList.add('no-photo');el.textContent='Foto em breve'}return el}
function cardPrice(p){if(p.options?.length)return 'A partir de '+money(Math.min(...p.options.map(x=>x.price)));return p.price!=null?money(p.price)+' / '+p.unit+(p.priceStatus==='referencia'?' · ref.':''):'Sob consulta'}
function renderCatalog(){const special=['sob-medida','buffet'].includes(view);document.querySelectorAll('#category-nav a').forEach(a=>{const active=a.hash==='#'+view;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});document.querySelectorAll('.special-section').forEach(s=>s.hidden=s.id!==view);$('#catalog-toolbar').hidden=special;$('#pagination').hidden=special;$('#menu-sections').hidden=special;$('#empty-results').hidden=true;$('#search-status').textContent='';if(special)return;
const result=CakeCatalog.selectProducts(CAKE_MENU,view,$('#search').value,page);page=result.page;$('#page-prev').disabled=page===1;$('#page-next').disabled=page===result.pages;$('#catalog-title').textContent=view==='balcao'?'Cardápio de balcão':groups.find(g=>g[0]===view)[1];$('#catalog-scope').textContent=groups.find(g=>g[0]===view)[3]==='balcao'?'PARA O SEU DIA A DIA':'PARA CELEBRAR COM A CAKE';$('#page-summary').textContent=result.total?`${result.start}–${result.end} de ${result.total} itens · Página ${page} de ${result.pages}`:'Nenhum item encontrado';$('#empty-results').hidden=result.total>0;
const grid=$('#menu-sections');grid.replaceChildren();for(const product of result.items){const button=document.createElement('button');button.className='product';button.dataset.id=product.id;button.setAttribute('aria-label',product.name+', '+cardPrice(product)+'. Ver opções');button.append(photo(product));const info=document.createElement('div');info.className='product-info';const tag=document.createElement('span');tag.className='product-tag';tag.textContent=groups.find(g=>g[0]===product.group)?.[1]||'Cake';const name=document.createElement('h3');name.textContent=product.name;const desc=document.createElement('p');desc.textContent=product.description;const bottom=document.createElement('div');bottom.className='product-bottom';const price=document.createElement('strong');price.textContent=cardPrice(product);const plus=document.createElement('span');plus.className='add-icon';plus.textContent='+';plus.setAttribute('aria-hidden','true');bottom.append(price,plus);info.append(tag,name,desc,bottom);button.append(info);button.onclick=()=>openProduct(product);grid.append(button)}
const pager=$('#pagination');pager.replaceChildren();if(result.total){const make=(label,target,disabled=false,current=false)=>{const b=document.createElement('button');b.textContent=label;b.disabled=disabled;if(current)b.setAttribute('aria-current','page');b.setAttribute('aria-label',typeof label==='number'?'Página '+label:label);b.onclick=()=>{page=target;renderCatalog();scrollCatalog();$('#catalog-title').focus({preventScroll:true})};return b};pager.append(make('← Anterior',page-1,page===1));for(let i=1;i<=result.pages;i++)pager.append(make(i,i,false,i===page));pager.append(make('Próxima →',page+1,page===result.pages))}}
$('#page-prev').onclick=()=>{page--;renderCatalog();scrollCatalog()};$('#page-next').onclick=()=>{page++;renderCatalog();scrollCatalog()};
$('#search').addEventListener('input',()=>{if(['sob-medida','buffet'].includes(view))view='encomendas';page=1;renderCatalog()});$('#clear-search').onclick=()=>{$('#search').value='';page=1;renderCatalog();$('#search').focus()};document.querySelectorAll('.occasion-link').forEach(a=>a.onclick=e=>{e.preventDefault();selectView('sob-medida')});window.addEventListener('hashchange',()=>selectView(location.hash.slice(1),false));document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!cart.open&&!detailDialog.open){e.preventDefault();$('#search').focus()}});
function variant(){const opt=selected.options?.[selectedOption];const base=opt?.price??selected.price??null;return {price:base==null?null:base+extraPrice(),unit:opt?.unit??selected.unit??'unidade',label:opt?.label||''}}
function updateDetail(){const v=variant();$('#detail-qty').textContent=number(selectedQty);$('#detail-minus').disabled=selectedQty<=(selected.minQty||1);$('#quantity-label').textContent='Quantidade em '+(v.unit==='kg'?'kg':v.unit==='cento'?'centos':v.unit==='meio cento'?'embalagens de 50 unidades':v.unit==='kit'?'kits':'unidades')+(selected.minQty>1?' · mínimo '+number(selected.minQty):'');$('#product-price').textContent=v.price==null?'Valor sob consulta':money(v.price)+' / '+v.unit+' · '+money(CakeCatalog.total(v.price,selectedQty));}
function openProduct(product){if(product.group==='bolos'){selectView('sob-medida');$('#cake-mass').value=product.mass;populateFlavors(product.id);return}selected=product;selectedQty=product.minQty||1;selectedOption=0;$('#product-category').textContent=groups.find(g=>g[0]===product.group)[1];$('#product-name').textContent=product.name;$('#product-description').textContent=product.description;$('#product-notes').value='';$('#detail-photo').replaceChildren(photo(product));$('#detail-photo').hidden=!product.image;$('#product-rules').textContent=product.rules||(product.scope==='balcao'?'Preço de referência pesquisado, não confirmado pela Cake. Confirme tamanho e disponibilidade do dia. Foto ilustrativa do tipo de produto; recheios e apresentação podem variar.':'Preço da tabela enviada pela Cake. Confirme disponibilidade e prazo antes de finalizar.');$('#product-option-label').hidden=!product.options?.length;$('#product-option').replaceChildren();product.options?.forEach((opt,i)=>{const o=document.createElement('option');o.value=i;o.textContent=opt.label+' — '+money(opt.price);$('#product-option').append(o)});renderExtras(product);updateDetail();detailDialog.showModal()}
$('#product-option').onchange=()=>{selectedOption=Number($('#product-option').value);selectedQty=selected.minQty||1;updateDetail()};$('#detail-minus').onclick=()=>{selectedQty=Math.max(selected.minQty||1,Math.round((selectedQty-(selected.step||1))*100)/100);updateDetail()};$('#detail-plus').onclick=()=>{selectedQty=Math.min(999,Math.round((selectedQty+(selected.step||1))*100)/100);updateDetail()};$('#confirm-add').onclick=()=>{if(!selected)return;const v=variant();add({id:selected.id,name:selected.name,detail:[$('#product-notes').value.trim(),v.label,extrasText()].filter(Boolean).join('\n'),reference:selected.priceStatus==='referencia',scope:selected.scope,qty:selectedQty,price:v.price,unit:v.unit,minQty:selected.minQty||1,step:selected.step||1});detailDialog.close()};$('#close-product').onclick=()=>detailDialog.close();
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),2400)}
function add(item){const old=items.find(i=>i.id===item.id&&i.detail===item.detail&&i.unit===item.unit);if(old)old.qty=Math.round((old.qty+item.qty)*100)/100;else items.push(item);renderCart();toast('Adicionado ao seu pedido')}
function renderCart(){const count=items.length;$('#count').textContent=count;$('#mobile-count').textContent=count;$('#mobile-cart').hidden=!count;const root=$('#cart-items');root.replaceChildren();$('#checkout').hidden=!count;if(!count){const p=document.createElement('p');p.textContent='Seu pedido está vazio. Escolha um item do cardápio para começar.';root.append(p);return}items.forEach((item,index)=>{const row=document.createElement('div');row.className='cart-item';const info=document.createElement('div');const title=document.createElement('strong');title.textContent=item.name;const detail=document.createElement('small');detail.textContent=(item.detail?item.detail+'\n':'')+number(item.qty)+' '+item.unit+' · '+(item.price==null?'Preço sob consulta':money(CakeCatalog.total(item.price,item.qty)));info.append(title,detail);const q=document.createElement('div');q.className='quantity';for(const [label,delta] of [['−',-1],['+',1]]){const b=document.createElement('button');b.textContent=label;b.setAttribute('aria-label',(delta===1?'Aumentar':'Diminuir')+' quantidade de '+item.name);b.onclick=()=>{const next=Math.round((item.qty+delta*item.step)*100)/100;if(next<item.minQty)items.splice(index,1);else item.qty=next;renderCart()};if(delta===1){const n=document.createElement('span');n.textContent=number(item.qty);q.append(n)}q.append(b)}const remove=document.createElement('button');remove.className='remove-item';remove.textContent='Remover';remove.onclick=()=>{items.splice(index,1);renderCart()};info.append(remove);row.append(info,q);root.append(row)});const known=items.filter(i=>i.price!=null),unknown=items.length-known.length;$('#cart-subtotal').textContent=(known.length?'Subtotal com preços informados: '+money(known.reduce((sum,i)=>sum+CakeCatalog.total(i.price,i.qty),0)): 'Valores sob consulta')+(unknown?' · '+unknown+' '+(unknown===1?'item a consultar':'itens a consultar'):'')+'. Adicionais escolhidos incluídos; decoração especial e tabuleiro a consultar.'+(items.some(i=>i.reference)?' Balcão: preços de referência, sujeitos à confirmação.':'');$('#copy-feedback').textContent='';$('#copy-fallback').hidden=true}
function openCart(){renderCart();cart.showModal()}$('#open-cart').onclick=openCart;$('#mobile-cart').onclick=openCart;$('#close-cart').onclick=()=>cart.close();for(const dialog of [cart,detailDialog])dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});

function renderExtras(p){const root=$('#product-extras');root.replaceChildren();const choose=(id,label,choices)=>{const l=document.createElement('label');l.textContent=label;const select=document.createElement('select');select.id=id;for(const name of choices){const o=document.createElement('option');o.textContent=name;select.append(o)}l.append(select);root.append(l);select.onchange=updateDetail};const check=(id,label)=>{const l=document.createElement('label');l.className='addon-checks';const input=document.createElement('input');input.type='checkbox';input.id=id;input.onchange=updateDetail;l.append(input,document.createTextNode(label));root.append(l)};
if(p.group==='combos'){choose('combo-flavor','Sabor do bolo',['Abacaxi com coco','Bombom','Brigadeiro','Dois amores','Prestígio','Quatro leites']);choose('combo-sweets','Doces',['Sortidos: brigadeiro, beijinho, cajuzinho e dois amores','Brigadeiro','Beijinho','Cajuzinho','Dois amores']);choose('combo-savory','Salgados',['Sortidos: coxinha, bolinha, pastel, risole e enroladinho','Coxinha','Bolinha de queijo','Pastel','Risole','Enroladinho de salsicha']);check('extra-topper','Topper (+ R$ 40,00 por kit)');if(Number(p.name.replace('Kit ',''))>=50)check('extra-tier','Bolo de andar (+ R$ 30,00 por kit; sabores permitidos)')}
if(['cake-81','cake-82','cake-83'].includes(p.id))check('extra-sprinkles','Granulado colorido (+ R$ 10,00 por cento; meio cento a consultar)');
if(p.name.includes('cupcake'))choose('cupcake-filling','Recheio',['Brigadeiro','Doce de leite']);}
function extraPrice(){let value=0;if($('#extra-topper')?.checked)value+=40;if($('#extra-tier')){const allowed=!['Abacaxi com coco','Quatro leites'].includes($('#combo-flavor').value);$('#extra-tier').disabled=!allowed;if(!allowed)$('#extra-tier').checked=false;if($('#extra-tier').checked)value+=30}if($('#extra-sprinkles')?.checked&&selected.options?.[selectedOption]?.unit==='cento')value+=10;return value}
function extrasText(){const a=[];for(const id of ['combo-flavor','combo-sweets','combo-savory','cupcake-filling'])if($('#'+id))a.push($('#'+id).parentElement.firstChild.textContent+': '+$('#'+id).value);if($('#extra-topper')?.checked)a.push('Topper incluído (+ R$ 40,00)');if($('#extra-tier')?.checked)a.push('Bolo de andar incluído (+ R$ 30,00)');if($('#extra-sprinkles')?.checked)a.push(selected.options?.[selectedOption]?.unit==='cento'?'Granulado colorido incluído (+ R$ 10,00/cento)':'Granulado colorido em meio cento: adicional a consultar');return a.join('\n').replaceAll('\\n','\n')}
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());$('#cake-date').min=today;$('#pickup-date').min=today;
function populateFlavors(id){const select=$('#cake-flavor');select.replaceChildren();CAKE_MENU.filter(p=>p.group==='bolos'&&p.mass===$('#cake-mass').value).forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name.replace('Bolo de ','')+' — '+money(p.price)+'/kg';select.append(o)});if(id)select.value=id;updateCake()}
function cakeState(){const p=CAKE_MENU.find(p=>p.id===$('#cake-flavor').value),weight=Number($('#cake-weight').value);const tierAllowed=weight>=5&&p.mass!=='branca';$('#cake-tier').disabled=!tierAllowed;if(!tierAllowed)$('#cake-tier').checked=false;const shine=$('#cake-shine').checked,topper=$('#cake-topper').checked,tier=$('#cake-tier').checked,cover=Number($('#cake-cover').value);const total=CakeCatalog.cakeTotal(p.price,weight,cover,shine,topper,tier);return {p,weight,shine,topper,tier,cover,total}}
function updateCake(){const c=cakeState();$('#cake-total').textContent='Total do bolo: '+money(c.total)+(c.tier?' + tabuleiro a consultar':'')}
$('#cake-mass').onchange=()=>populateFlavors();$('#cake-form').addEventListener('input',updateCake);$('#cake-flavor').onchange=updateCake;populateFlavors();
$('#cake-form').onsubmit=e=>{e.preventDefault();const c=cakeState();const details=[number(c.weight)+' kg · Massa '+c.p.mass,'Retirada desejada: '+$('#cake-date').value.split('-').reverse().join('/'),'Cobertura: '+$('#cake-cover').selectedOptions[0].textContent,c.shine?'Brilho (+ R$ 10,00)':'',c.topper?'Topper (+ R$ 40,00)':'',c.tier?'Bolo de andar (+ R$ 30,00); tabuleiro a consultar':'',$('#cake-details').value.trim()].filter(Boolean).join('\n').replaceAll('\\n','\n');add({id:'custom-'+c.p.id,name:c.p.name+' personalizado',detail:details,qty:1,price:c.total,unit:'bolo',minQty:1,step:1,scope:'encomendas'});if(!$('#pickup-date').value)$('#pickup-date').value=$('#cake-date').value;openCart()};
const orderReference='CK-'+Date.now().toString(36).toUpperCase();
function orderMessage(){const name=$('#customer').value.trim(),notes=$('#notes').value.trim();return `Olá, Cake! ${name?'Meu nome é '+name+'. ':''}Gostaria de fazer este pedido (${orderReference}):\n\n${items.map(i=>`${number(i.qty)} ${i.unit} — ${i.name} — ${i.price==null?'sob consulta':money(CakeCatalog.total(i.price,i.qty))}${i.reference?' (preço de referência)':''}${i.detail?'\n'+i.detail:''}`).join('\n\n')}\n\nRetirada desejada: ${$('#pickup-date').value?$('#pickup-date').value.split('-').reverse().join('/'):'a combinar'} ${$('#pickup-time').value}${notes?'\nObservações: '+notes:''}\n\n${$('#cart-subtotal').textContent}\nPodem confirmar os valores, a disponibilidade e o horário? Aguardarei a confirmação da Cake.`.replaceAll('\\n','\n')}
$('#whatsapp-order').onclick=()=>{if(!items.length)return;if(!$('#pickup-date').reportValidity()||!$('#pickup-time').reportValidity())return;const url='https://wa.me/554531981011?text='+encodeURIComponent(orderMessage());window.open(url,'_blank','noopener,noreferrer');$('#copy-feedback').textContent='Envie a mensagem no WhatsApp e aguarde a confirmação da Cake.'};
$('#copy-order').onclick=async()=>{const message=orderMessage();try{await navigator.clipboard.writeText(message);$('#copy-feedback').textContent='Resumo copiado! Cole na conversa com a Cake.'}catch{const fallback=$('#copy-fallback');fallback.hidden=false;fallback.value=message;fallback.focus();fallback.select();$('#copy-feedback').textContent='Copie o resumo abaixo e envie para a Cake.'}};
selectView(location.hash.slice(1)||'balcao',false);renderCart();
