const $=s=>document.querySelector(s);const cart=$('#cart'),detailDialog=$('#product-dialog'),items=[];let selected=null,selectedQty=1,toastTimer;
const groups=[['fritos','Salgados fritos','snack'],['assados','Salgados assados','snack'],['bebidas','Bebidas geladas','cup'],['sucos','Sucos e vitaminas','cup'],['quentes','Cafés e bebidas quentes','cup'],['bolos','Bolos e doces','cake'],['sob-medida','Bolos sob medida','cake'],['buffet','Buffet livre','snack']];
const icon=type=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${type==='cup'?'<path d="M5 8h12v9a4 4 0 0 1-4 4H9a4 4 0 0 1-4-4V8Z"/><path d="M17 9h2a3 3 0 0 1 0 6h-2M8 3v2m4-3v3"/>':type==='cake'?'<path d="M3 13h18v8H3zM3 13l9-6 9 6M12 7V3M6 17h12"/>':'<path d="M3 17h18M5 17v-2a7 7 0 0 1 14 0v2M12 6V4M9 21h6"/>'}</svg>`;
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
for(const [id,name,type]of groups){const a=document.createElement('a');a.href='#'+id;a.innerHTML=icon(type);const label=document.createElement('span');label.textContent=name;a.append(label);const count=CAKE_MENU.filter(p=>p.group===id).length;if(count){const small=document.createElement('small');small.textContent=count;a.append(small)}a.onclick=()=>{if($('#search').value){$('#search').value='';filterMenu()}setActive(id)};$('#category-nav').append(a)}
function setActive(id){document.querySelectorAll('#category-nav a').forEach(a=>{const active=a.hash==='#'+id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}
for(const [id,name,type]of groups.filter(g=>!['sob-medida','buffet'].includes(g[0]))){const section=document.createElement('section');section.className='menu-section';section.id=id;const title=document.createElement('div');title.className='section-title';title.innerHTML='<span>'+icon(type)+'</span>';const h=document.createElement('h2');h.textContent=name;const small=document.createElement('small');small.textContent=CAKE_MENU.filter(p=>p.group===id).length+' opções';title.append(h,small);const grid=document.createElement('div');grid.className='product-grid';for(const product of CAKE_MENU.filter(p=>p.group===id)){const button=document.createElement('button');button.className='product';button.dataset.id=product.id;button.dataset.search=normalize(product.name+' '+product.description);button.setAttribute('aria-label','Ver '+product.name);if(product.image){const img=document.createElement('img');img.src=product.image;img.alt='Imagem ilustrativa da categoria '+name.toLowerCase();img.loading='lazy';button.append(img)}else{const tile=document.createElement('span');tile.className='category-tile';tile.innerHTML=icon(type);button.append(tile)}const info=document.createElement('div');info.className='product-info';const n=document.createElement('h3');n.textContent=product.name;const d=document.createElement('p');d.textContent=product.description;const bottom=document.createElement('div');bottom.className='product-bottom';bottom.innerHTML='<strong>Sob consulta</strong><span class="add-icon" aria-hidden="true">+</span>';info.append(n,d,bottom);button.append(info);button.onclick=()=>openProduct(product);grid.append(button)}section.append(title,grid);$('#menu-sections').append(section)}
function filterMenu(){const term=normalize($('#search').value.trim());let visible=0;document.querySelectorAll('.product').forEach(p=>{p.hidden=!p.dataset.search.includes(term);if(!p.hidden)visible++});document.querySelectorAll('.menu-section').forEach(s=>s.hidden=![...s.querySelectorAll('.product')].some(p=>!p.hidden));document.querySelectorAll('.special-section').forEach(s=>s.hidden=!!term&&!normalize(s.textContent).includes(term));$('#search-status').textContent=term?`${visible} ${visible===1?'item encontrado':'itens encontrados'} no cardápio`:'';$('#empty-results').hidden=visible>0||[...document.querySelectorAll('.special-section')].some(s=>!s.hidden);if(term)setActive('')}
$('#search').addEventListener('input',filterMenu);$('#clear-search').onclick=()=>{$('#search').value='';filterMenu();$('#search').focus()};document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&!cart.open&&!detailDialog.open){e.preventDefault();$('#search').focus()}});
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{if($('#search').value)return;const entry=entries.find(e=>e.isIntersecting);if(entry)setActive(entry.target.id)},{rootMargin:'-180px 0px -50% 0px',threshold:0});document.querySelectorAll('.menu-section,.special-section').forEach(s=>observer.observe(s))}setActive('fritos');
function openProduct(product){selected=product;selectedQty=1;$('#detail-qty').textContent=1;$('#product-category').textContent=groups.find(g=>g[0]===product.group)[1];$('#product-name').textContent=product.name;$('#product-description').textContent=product.description;$('#product-notes').value='';detailDialog.showModal()}
$('#detail-minus').onclick=()=>{$('#detail-qty').textContent=selectedQty=Math.max(1,selectedQty-1)};$('#detail-plus').onclick=()=>{$('#detail-qty').textContent=selectedQty=Math.min(999,selectedQty+1)};$('#confirm-add').onclick=()=>{if(selected)add(selected.name,$('#product-notes').value.trim(),selectedQty);detailDialog.close()};$('#close-product').onclick=()=>detailDialog.close();
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),2400)}
function add(name,detail='',qty=1){const old=items.find(i=>i.name===name&&i.detail===detail);if(old)old.qty+=qty;else items.push({name,detail,qty});render();toast('Adicionado ao seu pedido')}
function render(){const count=items.reduce((n,i)=>n+i.qty,0);$('#count').textContent=count;$('#mobile-count').textContent=count;$('#mobile-cart').hidden=!count;const root=$('#cart-items');root.replaceChildren();$('#checkout').hidden=!items.length;if(!items.length){const p=document.createElement('p');p.textContent='Seu pedido está vazio. Escolha uma opção no cardápio para começar.';root.append(p);return}items.forEach((item,index)=>{const row=document.createElement('div');row.className='cart-item';const info=document.createElement('div');const title=document.createElement('strong');title.textContent=item.name;info.append(title);if(item.detail){const detail=document.createElement('small');detail.textContent=item.detail;info.append(detail)}const q=document.createElement('div');q.className='quantity';for(const [label,value]of [['−',-1],['+',1]]){const b=document.createElement('button');b.textContent=label;b.setAttribute('aria-label',(value===1?'Aumentar':'Diminuir')+' quantidade de '+item.name);b.onclick=()=>{item.qty+=value;if(!item.qty)items.splice(index,1);render()};if(value===1){const count=document.createElement('span');count.textContent=item.qty;q.append(count)}q.append(b)}row.append(info,q);root.append(row)});$('#copy-feedback').textContent='';$('#copy-fallback').hidden=true}
function openCart(){render();cart.showModal()}$('#open-cart').onclick=openCart;$('#mobile-cart').onclick=openCart;$('#close-cart').onclick=()=>cart.close();for(const dialog of [cart,detailDialog])dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
const dateInput=$('#cake-date');const now=new Date();dateInput.min=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');$('#cake-form').onsubmit=e=>{e.preventDefault();const date=dateInput.value.split('-').reverse().join('/');add('Bolo sob medida',`Data: ${date}\nPessoas: ${$('#cake-people').value}\nIdeia: ${$('#cake-details').value.trim()}`);cart.showModal()};
$('#copy-order').onclick=async()=>{const name=$('#customer').value.trim();const notes=$('#notes').value.trim();const message=`Olá, Cake! ${name?'Meu nome é '+name+'. ':''}Gostaria de consultar este pedido:\n\n${items.map(i=>`${i.qty} × ${i.name}${i.detail?'\n'+i.detail:''}`).join('\n\n')}${notes?'\n\nObservações: '+notes:''}\n\nPodem confirmar valores, disponibilidade e como combinar a retirada?`;const feedback=$('#copy-feedback');try{await navigator.clipboard.writeText(message);feedback.textContent='Resumo copiado! Agora abra o Instagram e cole na conversa com a Cake.'}catch{const fallback=$('#copy-fallback');fallback.hidden=false;fallback.value=message;fallback.focus();fallback.select();feedback.textContent='Selecione e copie o resumo abaixo. Depois, cole na conversa no Instagram.'}};render();
